### ISSUE TITLE
Problem running examples

### ISSUE THREAD

**Issue by terryfrankcombe** [NVIDIA/TorchFort#61]
Hi folks

I am excited about the possibilities opened up by torchfort.  However, I am struggling to get off the ground.  Specifically the examples aren't running effectively.

I'm on a machine with V100 cards.  make finished successfully.  Am running with cuda/12.5.1, nccl/2.27.5, torch==2.7.0, nvidia-cuda-runtime-cu12==12.6.77 etc.

**cpp/cart_pole**
When I execute the cpp/cart_pole example code it runs successfully.  However, nvidia-smi shows it's not using the GPU, despite the comment in the README that it uses the GPU for training.  Digging a bit deeper I find that ENABLE_GPU is not enabled when it is being built.  ENABLE_GPU is defined when building the library, and ENABLE_GPU is referred to in cart_pole's train.cpp to switch on the GPU device and trigger CUDA calls.  Why is this?

**fortran/graph**
When I execute the fortran/graph example code, it crashes straight away with:

> Traceback of TorchScript, original code (most recent call last):
>   File "/scratch/y35/tjf502/TorchFort/examples/fortran/graph/generate_loss.py", line 42, in forward
>     # Zero out error for boundary nodes
>     mask = node_types != 0
>     err *= mask.unsqueeze(-1)
>     ~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
>   
>     # Compute mean over non-boundary nodes
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
> 

I don't know how to debug this yet.  Any ideas on whether this is a configuration problem or something in the code?

**Comment by terryfrankcombe** [comment]
Excellent, thanks @romerojosh.  Those branches merged in and fixed my problems.

cart_pole did not stress my V100 at all, managing to raise the power usage by about 10 W ;-)
graph did better, with about 30% util.

Thank you for responding so quickly.

**Comment by azrael417** [comment]
Hello Terry, cart pole is super small, it is not supposed to stress the GPU, it is also runnable on CPU. Happy it works now.
